# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-7.0:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.0-jessie-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/php70

    steps:
      - checkout
      - run:
          name: Install ClickHouse
          command: |
            sudo apt-get install software-properties-common
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
            echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
            sudo apt-get update
            sudo apt-get install clickhouse-server-common -y
            sudo apt-get install clickhouse-client -y
            sudo sed -e "/<listen_host>::1<\/listen_host>/d" -i /etc/clickhouse-server/config.xml
            sudo service clickhouse-server start

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit
  build-7.1:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-fpm-jessie-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/php71

    steps:
      - checkout
      - run:
          name: Install ClickHouse
          command: |
            sudo apt-get install software-properties-common
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
            echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
            sudo apt-get update
            sudo apt-get install clickhouse-server-common -y
            sudo apt-get install clickhouse-client -y
            sudo sed -e "/<listen_host>::1<\/listen_host>/d" -i /etc/clickhouse-server/config.xml
            sudo service clickhouse-server start

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit
  build-7.2:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-fpm-stretch-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/php72

    steps:
      - checkout
      - run:
          name: Install ClickHouse
          command: |
            sudo apt-get install software-properties-common
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
            echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list
            sudo apt-get update
            sudo apt-get install clickhouse-server-common -y
            sudo apt-get install clickhouse-client -y
            sudo sed -e "/<listen_host>::1<\/listen_host>/d" -i /etc/clickhouse-server/config.xml
            sudo service clickhouse-server start

      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit

workflows:
  version: 2
  default:
    jobs:
      - build-7.0
      - build-7.1
      - build-7.2